"""Type stubs for ArrowDB native module."""

from __future__ import annotations
from enum import Enum
from typing import Callable, Sequence, overload

# Type aliases
Metadata = dict[str, int | float | str | bool]
Vector = Sequence[float]

class Space(Enum):
    COSINE: int
    L2: int
    INNER_PRODUCT: int

class IndexType(Enum):
    HNSW: int

class Quantization(Enum):
    NONE: int
    INT8: int

class FieldType(Enum):
    INT64: int
    DOUBLE: int
    STRING: int
    BOOL: int

class StatusCode(Enum):
    OK: int
    INVALID_ARGUMENT: int
    NOT_FOUND: int
    ALREADY_EXISTS: int
    UNIMPLEMENTED: int
    DIMENSION_MISMATCH: int
    IO_ERROR: int
    EOF: int
    CORRUPTION: int
    CHECKSUM_MISMATCH: int
    BAD_RECORD: int
    BAD_HEADER: int
    VERSION_MISMATCH: int
    INTERNAL: int

class ArrowDBError(RuntimeError): ...

class HNSWParams:
    M: int
    ef_construction: int
    ef_search: int
    def __init__(self, M: int = 16, ef_construction: int = 200, ef_search: int = 200) -> None: ...

class IndexConfig:
    index_type: IndexType
    max_elements: int
    quantization: Quantization
    hnsw_params: HNSWParams
    def __init__(
        self,
        index_type: IndexType = ...,
        max_elements: int = 1000000,
        quantization: Quantization = ...,
        hnsw_params: HNSWParams = ...,
    ) -> None: ...

class FieldDef:
    name: str
    type: FieldType
    required: bool
    def __init__(self, name: str, type: FieldType, required: bool = False) -> None: ...

class MetadataSchema:
    def __init__(self) -> None: ...
    def field(self, name: str, type: FieldType, required: bool = False) -> MetadataSchema: ...
    def empty(self) -> bool: ...

class CollectionConfig:
    name: str
    dimensions: int
    space: Space
    index_config: IndexConfig
    schema: MetadataSchema
    def __init__(
        self,
        name: str,
        dimensions: int,
        space: Space = ...,
        index_config: IndexConfig = ...,
    ) -> None: ...

class ClientOptions:
    data_dir: str
    default_index_config: IndexConfig
    def __init__(self, data_dir: str) -> None: ...

class Document:
    id: str
    embedding: list[float]
    metadata: Metadata
    def __init__(
        self,
        embedding: Vector,
        metadata: Metadata = ...,
        id: str = "",
    ) -> None: ...

class InsertResult:
    @property
    def id(self) -> str: ...
    @property
    def ok(self) -> bool: ...
    @property
    def message(self) -> str: ...

class BatchInsertResult:
    @property
    def results(self) -> list[InsertResult]: ...
    @property
    def success_count(self) -> int: ...
    @property
    def failure_count(self) -> int: ...

class ScoredDocument:
    @property
    def id(self) -> str: ...
    @property
    def score(self) -> float: ...
    @property
    def metadata(self) -> Metadata: ...

class SearchResult:
    @property
    def hits(self) -> list[ScoredDocument]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> ...: ...

class IndexSearchResult:
    @property
    def id(self) -> str: ...
    @property
    def score(self) -> float: ...

class CollectionStats:
    @property
    def vector_count(self) -> int: ...
    @property
    def metadata_count(self) -> int: ...
    @property
    def max_capacity(self) -> int: ...
    @property
    def dimensions(self) -> int: ...

class MetadataFilter:
    def __init__(self, predicate: Callable[[Metadata], bool]) -> None: ...
    @staticmethod
    def eq(field: str, value: int | float | str | bool) -> MetadataFilter: ...
    @staticmethod
    def neq(field: str, value: int | float | str | bool) -> MetadataFilter: ...
    @staticmethod
    def gt(field: str, value: int | float) -> MetadataFilter: ...
    @staticmethod
    def gte(field: str, value: int | float) -> MetadataFilter: ...
    @staticmethod
    def lt(field: str, value: int | float) -> MetadataFilter: ...
    @staticmethod
    def lte(field: str, value: int | float) -> MetadataFilter: ...
    @staticmethod
    def in_(field: str, values: list[int | float | str | bool]) -> MetadataFilter: ...
    @staticmethod
    def and_(a: MetadataFilter, b: MetadataFilter) -> MetadataFilter: ...
    @staticmethod
    def or_(a: MetadataFilter, b: MetadataFilter) -> MetadataFilter: ...
    @staticmethod
    def not_(filter: MetadataFilter) -> MetadataFilter: ...
    def __call__(self, metadata: Metadata) -> bool: ...

class Collection:
    def __init__(self, config: CollectionConfig) -> None: ...
    @staticmethod
    def create(config: CollectionConfig, path: str) -> Collection: ...
    @staticmethod
    def load(path: str) -> Collection: ...
    @property
    def name(self) -> str: ...
    @property
    def dimension(self) -> int: ...
    @property
    def space(self) -> Space: ...
    def __len__(self) -> int: ...
    @overload
    def insert(self, embedding: Vector, metadata: Metadata = ...) -> str: ...
    @overload
    def insert(self, id: str, embedding: Vector, metadata: Metadata = ...) -> None: ...
    def insert_doc(self, doc: Document) -> str: ...
    def insert_batch(self, documents: list[Document]) -> BatchInsertResult: ...
    def get(self, id: str) -> list[float]: ...
    def update(self, id: str, embedding: Vector, metadata: Metadata = ...) -> None: ...
    def upsert(self, id: str, embedding: Vector, metadata: Metadata = ...) -> None: ...
    def remove(self, id: str) -> None: ...
    @overload
    def search(self, query: Vector, k: int, ef: int = 200) -> list[IndexSearchResult]: ...
    @overload
    def search(self, query: Vector, k: int, filter: MetadataFilter, ef: int = 200) -> list[IndexSearchResult]: ...
    @overload
    def query(self, query: Vector, k: int, ef: int = 200) -> SearchResult: ...
    @overload
    def query(self, query: Vector, k: int, filter: MetadataFilter, ef: int = 200) -> SearchResult: ...
    def search_batch(self, queries: list[list[float]], k: int, ef: int = 200) -> list[list[IndexSearchResult]]: ...
    def set_metadata(self, id: str, metadata: Metadata) -> None: ...
    def get_metadata(self, id: str) -> Metadata: ...
    def optimize(self) -> None: ...
    def save(self, path: str) -> None: ...
    def close(self) -> None: ...
    def recovered_from_wal(self) -> bool: ...
    def stats(self) -> CollectionStats: ...

class CollectionRef:
    """Non-owning reference to a Collection managed by a Client."""
    @property
    def name(self) -> str: ...
    @property
    def dimension(self) -> int: ...
    @property
    def space(self) -> Space: ...
    def __len__(self) -> int: ...
    @overload
    def insert(self, embedding: Vector, metadata: Metadata = ...) -> str: ...
    @overload
    def insert(self, id: str, embedding: Vector, metadata: Metadata = ...) -> None: ...
    def insert_batch(self, documents: list[Document]) -> BatchInsertResult: ...
    def get(self, id: str) -> list[float]: ...
    def update(self, id: str, embedding: Vector, metadata: Metadata = ...) -> None: ...
    def upsert(self, id: str, embedding: Vector, metadata: Metadata = ...) -> None: ...
    def remove(self, id: str) -> None: ...
    @overload
    def search(self, query: Vector, k: int, ef: int = 200) -> list[IndexSearchResult]: ...
    @overload
    def search(self, query: Vector, k: int, filter: MetadataFilter, ef: int = 200) -> list[IndexSearchResult]: ...
    @overload
    def query(self, query: Vector, k: int, ef: int = 200) -> SearchResult: ...
    @overload
    def query(self, query: Vector, k: int, filter: MetadataFilter, ef: int = 200) -> SearchResult: ...
    def search_batch(self, queries: list[list[float]], k: int, ef: int = 200) -> list[list[IndexSearchResult]]: ...
    def set_metadata(self, id: str, metadata: Metadata) -> None: ...
    def get_metadata(self, id: str) -> Metadata: ...
    def optimize(self) -> None: ...
    def save(self, path: str) -> None: ...
    def close(self) -> None: ...
    def stats(self) -> CollectionStats: ...

class Client:
    @overload
    def __init__(self, data_dir: str) -> None: ...
    @overload
    def __init__(self, options: ClientOptions) -> None: ...
    def __enter__(self) -> Client: ...
    def __exit__(self, *args: object) -> bool: ...
    def create_collection(self, name: str, config: CollectionConfig) -> CollectionRef: ...
    def get_collection(self, name: str) -> CollectionRef: ...
    @overload
    def get_or_create_collection(self, name: str, config: CollectionConfig) -> CollectionRef: ...
    @overload
    def get_or_create_collection(self, name: str) -> CollectionRef: ...
    def drop_collection(self, name: str) -> None: ...
    def list_collections(self) -> list[str]: ...
    def has_collection(self, name: str) -> bool: ...
    def close(self) -> None: ...
    @property
    def data_dir(self) -> str: ...
